# demo_setup.yml

- hosts: servers
  gather_facts: True
  vars:
    service_account_file: /etc/gcp/dbaas-test-268007.json
    project: dbaas-test-268007
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  roles:
    - ./roles/getGcpInfo

- hosts: mysql
  gather_facts: True

  roles:
    - ./roles/start-dm
