# demo_setup.yml

- hosts: servers
  gather_facts: True
  vars:
    service_account_file: /etc/gcp/dbaas-test-268007.json
    project: dbaas-test-268007
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute
        #  environment:
        #PYTHONPATH: "{{ ansible_env.PYTHONPATH }}:/my/path"

  roles:
      - ./roles/getGcpInfo

- hosts: tidb_workstation
  gather_facts: True

  roles:
      - ../tidb/playbook/roles/install
