# demo_setup.yml

- hosts: servers
  gather_facts: True
  roles:
    - ./roles/getGcpInfo

- hosts: mysql
  gather_facts: True

  roles:
    - ../base/playbook/roles/general
    - ../base/playbook/roles/docker
    - ../mysql/playbook/roles/single
    - ./roles/wordpress
    - ../roles/dm
