# demo_setup.yml

- hosts: servers
  gather_facts: True
  vars:
    service_account_file: /etc/gcp/sales-demo.json
    project: sales-demo-321300
    auth_kind: serviceaccount
    scopes:
      - https://www.googleapis.com/auth/compute

  roles:
    - ./roles/getGcpInfo

- hosts: mysql
  gather_facts: True

  roles:
    - ../base/playbook/roles/general
    - ../base/playbook/roles/docker
    - ../mysql/playbook/roles/single
    - ./roles/wordpress
    - ../roles/dm
