- name: Set the OS architect
  shell: dpkg --print-architecture
  register: os_arch

- name: set the OS architect
  set_fact:
    os_arch: "{{ os_arch['stdout_lines'][0] }}"
    os_id: "{{ ansible_facts['lsb']['id'] | lower }}"

- name: Print the os arch
  debug:
    var=os_arch

- name: Print the os id
  debug:
    var=os_id

- name: Print all the info
  debug:
    var=ansible_facts['lsb']['codename']

- name: Remove the docker repo file before update
  become: yes
  file:
      path: /etc/apt/sources.list.d/docker.list
      state: absent

- name: Update repositories cache and install docker dependency packages
  become: yes
  apt:
    name: 
      - python-apt
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    update_cache: yes

- name: 1.2 Download the key
  when: True
  shell: |
    curl -fsSL https://download.docker.com/linux/{{os_id}}/gpg | sudo gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
  args:
    executable: /bin/bash

- name: 1.3 Install the repository
  when: True
  shell: |
      echo \
        "deb [arch={{os_arch}} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/{{os_id}} \
           $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash

- name: 1.4 Docker installation
  become: yes
  apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose
    update_cache: yes

- name: Add the user 'pi' to the group 'docker'
  become: yes
  ansible.builtin.user:
    name: pi
    groups: pi,docker,sudo,adm,users
