# # Global variables are applied to all deployments and used as the default value of
# # the deployments if a specific deployment value is missing.
global:
  user: "tidb"
  ssh_port: 22
  deploy_dir: "/DATA/deploy"
  data_dir: "/DATA/data"

pd_servers:
  - host: 192.168.1.101
    arch: "{{ ARCH  }}"
  - host: 192.168.1.102
    arch: "{{ ARCH  }}"
  - host: 192.168.1.103
    arch: "{{ ARCH  }}"

tidb_servers:
  - host: 192.168.1.108
    arch: "{{ ARCH  }}"
  - host: 192.168.1.109
    arch: "{{ ARCH  }}"

tikv_servers:
  - host: 192.168.1.104
    arch: "{{ ARCH  }}"
  - host: 192.168.1.105
    arch: "{{ ARCH  }}"
  - host: 192.168.1.106
    arch: "{{ ARCH  }}"

monitoring_servers:
  - host: 192.168.1.107
    arch: "{{ ARCH  }}"

grafana_servers:
  - host: 192.168.1.107
    arch: "{{ ARCH  }}"

alertmanager_servers:
  - host: 192.168.1.107
    arch: "{{ ARCH  }}"
