version: '2.0'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "{{ WORDPRESS_TIDB_PORT }}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: {{ componentIPs['tidb'] | first }}:4000
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
