version: '2.0'

services:
  wordpress_mariadb:
    image: wordpress:latest
    ports:
      - "{{ WORDPRESS_PORT }}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: {{ gatewayIP }}:3306
      WORDPRESS_DB_USER: {{ MYSQL_DBUSER }}
      WORDPRESS_DB_PASSWORD: {{ MYSQL_DBPASSWD }}
    networks:
      - wordpress_mariadb
networks:
  wordpress_mariadb:
