- name: Get the data from upstream tasks
  set_fact:
    componentIPs: "{{ hostvars['localhost'].get('componentIPs')['resources'] }}"

- name: Get the data from upstream tasks
  set_fact:
    gatewayIP: "{{ hostvars['localhost'].get('componentIPs')['resources']['externalIP'] }}"

- name: Pull wordpres images from remote
  become: yes
  become_user: mysql
  shell: docker pull wordpress
    #- name: Pull wordpres images from remote
    #  become: yes
    #  become_user: mysql
    #  docker_image:
    #    name: wordpress
    #    source: pull

- name: directory preparation
  become: yes
  file:
    path: /var/docker-compose/wordpress
    owner: mysql
    group: mysql
    state: directory

- name: docker compose deployment
  become: yes
  template:
    src: "{{ item.src  }}"
    dest: "/var/docker-compose/wordpress/{{ item.dest }}"
    owner: mysql
    group: mysql
    mode: u=rw,g=r,o=r
  loop:
    - { src: docker-compose.yml,      dest: docker-compose.yml      }
    - { src: docker-compose.tidb.yml, dest: docker-compose.tidb.yml }

- name: Start the mariadb
  become: yes
  become_user: mysql
  shell: /usr/bin/docker-compose -f /var/docker-compose/mariadb/docker-compose.yml up -d

- name: Grant permission to wordpress
  shell: "{{item}}"
  with_items:
      - "mysql -h {{ componentIPs['workstation'] | first }} -u root -P 3306 -ppasswd wordpress -e 'GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT, REPLICATION MASTER ADMIN ON *.* TO `wordpress`@`%`'"
      - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'create database if not exists wordpress'"
      - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'create user if not exists wordpress@`%` identified by \"wordpress\"'"
      - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'grant select, update, insert, delete on wordpress.* to `wordpress`@`%`'"
      - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'set global tidb_enable_noop_functions=on'"

- name: Start the mariadb
  become: yes
  become_user: mysql
  shell: /usr/bin/docker-compose -f /var/docker-compose/wordpress/docker-compose.yml up -d
