- name: Install the linux arm to /usr/local
  become: yes
  ansible.builtin.unarchive:
    src: https://golang.org/dl/go1.16.4.linux-arm64.tar.gz
    dest: /opt
    remote_src: yes

- name: Add GOROOT to the .bashrc.local
  become: yes
  lineinfile:
    path: /home/pi/.bashrc.local
    line: export GOROOT=/opt/go
