- name: Install the linux arm to /usr/local
  ansible.builtin.unarchive:
    src: https://golang.org/dl/go1.16.4.linux-arm64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy bin files to /usr/local/bin
  become: yes
  shell: "cp /tmp/go/bin/{{ item  }} /usr/local/bin/"
  loop:
    - go
    - gofmt

- name: Delete content & directory
  file:
    state: absent
    path: /tmp/go

