all:
    hosts:
        workstation:
            ansible_connection: ssh
            ansible_host: 192.168.1.166
            ansible_port: 22
            ansible_user: pi
workstation:
    hosts:
        workstation:
