---
- name: Deploy the tmux in the workstation
  hosts: workstation
  tags:
      - tmux
  roles:
      - ./roles/tmux

- name: Deploy the zsh in the workstation
  hosts: workstation
  tags:
      - zsh
  roles:
      - ./roles/zsh

- name: Deploy the cht in the workstation
  hosts: workstation
  tags:
      - cht
  roles:
      - ./roles/cht
