- name: 01.01 Test the gcp_compute_target_pool_instance
  when: false
  gcp_compute_target_pool_instance:
    name: tidbtargetpool
    region: 'asia-northeast1'
    state: present
    filters:
    - labels.component = scale-tidb
    project:              "{{ project              }}"
    auth_kind:            "{{ auth_kind            }}"
    service_account_file: "{{ service_account_file }}"
    scopes:               "{{ scopes               }}"

- name: 01.01 Test the gcp_compute_target_pool_instance
  when: true
  gcp_compute_target_pool_instance:
    name: tidbtargetpool
    region: 'asia-northeast1'
    state: absent
    instances:
      - ins-dmm-tidb-scale-0
      - ins-dmm-tidb-scale-1
    project:              "{{ project              }}"
    auth_kind:            "{{ auth_kind            }}"
    service_account_file: "{{ service_account_file }}"
    scopes:               "{{ scopes               }}"
  register: poolvalue

# gcloud compute target-pools add-instances tidbtargetpool --instances ins-dmm-tidb-scale-0 --instances-zone=asia-northeast1-b
# gcloud compute target-pools add-instances tidbtargetpool --instances ins-dmm-tidb-scale-1 --instances-zone=asia-northeast1-a
