{% for server in MONITORING_TARGET %}
object Host "{{ server.NAME }}" {
  import "generic-host"

  address = "{{ server.IP }}"

  vars.os = "Linux"

  vars.http_vhosts["http"] = {
    http_uri = "/"
  }

  vars.disks["disk"] = {
  }
  vars.disks["disk /"] = {
    disk_partitions = "/"
  }

  vars.notification["mail"] = {
    groups = [ "icingaadmins" ]
  }
}
{% endfor %}
