version: '2.0'

services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    volumes:
      - /var/docker-compose/mariadb/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
    environment:
      MYSQL_ROOT_PASSWORD: {{ MYSQL_ROOT_PASSWD | default('passwd') }}
      MYSQL_DATABASE: {{ MYSQL_DBNAME | default('testdb') }}
      MYSQL_USER: {{ MYSQL_DBUSER | default('testdbuser') }}
      MYSQL_PASSWORD: {{ MYSQL_DBPASSWD | default('testdbpasswd') }}

