- name: 01.01 Create tidb group
  become: yes
  group:
    name: tidb
    state: present
    gid: "{{GROUP.tidb}}"

- name: 01.02 Create tidb user
  become: yes
  user:
    name: tidb
    state: present
    group: tidb
    uid: "{{USER.tidb}}"

- name: 02.01 tiup bin download
  become: yes
  get_url:
    url: https://tiup-mirrors.pingcap.com/install.sh
    dest: /tmp/install.sh
    owner: "{{TIDB_USER}}"
    group: "{{TIDB_USER}}"
    mode: "0755"

- name: 02.02 tiup installation
  become: yes
  become_user: "{{TIDB_USER}}"
  shell: /tmp/install.sh

- name: 02.03 Add the search path into ~/.bashrc
  become: yes 
  lineinfile:
    path: "/home/{{TIDB_USER}}/.bashrc"
    line: "export PATH=/home/{{TIDB_USER}}/.tiup/bin:$PATH"

- name: 03.01 prepare the .ssh folder
  become: yes
  file:
    path: "/home/{{TIDB_USER}}/.ssh"
    owner: "{{TIDB_USER}}"
    group: "{{TIDB_USER}}"
    state: directory
    mode: "0700"
 
- name: 03.02 ssh key file deployment
  become: yes
  copy:
     src: "tidb_rsa_key"
     dest: "/home/{{TIDB_USER}}/.ssh/id_rsa"
     decrypt: yes

- name: 03.03 config file
  become: yes
  copy:
    dest: "/home/{{TIDB_USER}}/.ssh/config"
    content: StrictHostKeyChecking no
    owner: "{{TIDB_USER}}"
    group: "{{TIDB_USER}}"
    mode: "0600"

- name: Prepare the folder workstation
  become: yes
  ansible.builtin.file:
    path: "/home/{{TIDB_USER}}/workstation"
    state: directory
    owner: "{{TIDB_USER}}"
    group: "{{TIDB_USER}}"

- name: Download the script to add debian repository
  when: ansible_os_family == "Debian"
  get_url:
    url: https://packagecloud.io/install/repositories/akopytov/sysbench/script.deb.sh
    dest: /tmp/script.sh
    mode: '0755'

- name: Download the script to add yum repository
  when: ansible_os_family in  [ "CentOS" , "RedHat" ]
  get_url:
    url: https://packagecloud.io/install/repositories/akopytov/sysbench/script.rpm.sh
    dest: /tmp/script.sh
    mode: '0755'

- name: Add the sysbench repository for CentOS
  become: yes
  shell: /tmp/script.sh

- name: Install the required packages
  become: yes
  when: ansible_os_family == "Debian"
  ansible.builtin.apt:
    name:
      - mariadb-client
      - sysbench

- name: Install the required packages
  become: yes
  ansible.builtin.package:
    name:
      - mariadb
      - sysbench
      - git
      - gcc

- name: 12.01 Golang installation
  become: yes
  unarchive:
    src: https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
    remote_src: yes
    dest: /usr/local

- name: 12.02 Add go path
  lineinfile:
    path: ~/.bashrc
    line: "export PATH=/usr/local/go/bin:$PATH"

- name: 12.02 Prepare the directory for ycsn workload
  become: yes
  file:
    path: /etc/ycsb
    state: directory

- name: 12.02 Download git source code
  ansible.builtin.git:
    repo: https://github.com/pingcap/go-ycsb.git
    dest: /tmp/go-ycsb

- name: 12.03 Compile the source code
  shell: "{{item}}"
  args:
    chdir: /tmp/go-ycsb
  with_items:
    - make
    - sudo cp bin/go-ycsb /usr/local/bin/
    - sudo cp -r workloads /etc/ycsb/

- name: 13 Resource clean
  become: yes
  file:
    path: /tmp/go-ycsb
    state: absent
  with_items:
    - /tmp/go-ycsb
    - /tmp/script.sh
