- name: 1.1 emacs - Download emacs source code
  when: false
  unarchive:
    src: "http://ftp.jaist.ac.jp/pub/GNU/emacs/emacs-{{ EMACS_VERSION }}.tar.xz"
    dest: /tmp
    remote_src: yes

- name: 1.2 compilation
  when: false
  shell: | 
    sh autogen.sh
    ./configure --prefix={{ INSTALL_DIR }}/emacs/{{ EMACS_VERSION }} --without-x
    make
    sudo make install
  args:
    executable: /bin/bash
    chdir: "{{ TMP_DIR }}/emacs-{{ EMACS_VERSION }}"

- name: 1.3 Git checkout
  when: false
  ansible.builtin.git:
    repo: 'https://github.com/syl20bnr/spacemacs.git'
    dest: /home/pi/.emacs.d
    version: v0.200.13

- name: 1.4 Set the PATH to run emacs
  when: false
  become: yes
  lineinfile:
    path: /home/pi/.bashrc.local
    line: export PATH=/opt/emacs/27.2/bin:$PATH

- name: 1.5 copy service file
  when: false
  become: yes
  copy:
    src: emacs.service
    dest: /etc/systemd/system/emacs.service
    owner: root
    group: root
    mode: 0644

- name: 1.6 Restart the emacs service
  when: false
  become: yes
  service:
    name: emacs
    state: restarted

- name: 1.7.1 Install packages for plantuml
  when: false
  become: yes
  apt:
    name: "{{ item  }}"
  loop:
    - openjdk-11-jre
    - graphviz

- name: 1.7.2 prepare the directory
  become: yes
  file:
    state: directory
    path: /opt/emacs/lib
    owner: root
    group: root
    mode: 0755

- name: 1.7.3 Download plantuml
  become: yes
  get_url:
    url: https://sourceforge.net/projects/plantuml/files/plantuml.1.2021.7.jar
    dest: /opt/emacs/lib/plantuml.1.2021.7.jar
    owner: root
    group: root

- name: 1.7.4 Make one soft link to plantuml
  become: yes
  file:
    src: /opt/emacs/lib/plantuml.1.2021.7.jar
    dest: /opt/emacs/lib/plantuml.jar
    owner: root
    group: root
    state: link

- name: 1.7.5
  become: yes
  blockinfile:
    path: /home/pi/.emacs.d/init.el
    marker: ";; {mark} ANSIBLE MANAGED BLOCK"
    block: |
      (setq org-plantuml-jar-path "/opt/emacs/lib/plantuml.jar")
      (org-babel-do-load-languages
        'org-babel-load-languages
        '((plantuml . t)))
    

# https://github.com/purcell/emacs.d
# https://github.com/syl20bnr/spacemacs ~/.emacs.d

