- name: Get the data from upstream tasks
  set_fact:
    ALL_CLUSTER_IPS: "{{ hostvars['localhost'].get('ALL_CLUSTER_IPS')   }}"
    PD_IPS:          "{{ hostvars['localhost'].get('PD_IPS')            }}"
    KV_IPS:          "{{ hostvars['localhost'].get('KV_IPS')            }}"

- name: Print all the IPS
  debug:
    var=ALL_CLUSTER_IPS

- name: Print PD Ips
  debug:
    var=PD_IPS

- name: 01. Prepare the workstation 
  become: yes
  file:
    path: /opt/ycsb
    state: directory
    mode: '0755'

- name: 02. Deploy all the templates
  become: yes
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "/opt/ycsb/{{ item.dest }}"
    mode: "{{item.mode}}"
  with_items:
    - {src: "initServers.sh.template"   ,     dest: "initServers.sh", mode: "0755" }
    - {src: "deploy.yml.template"       ,     dest: "deploy.yml"    , mode: "0644" }
    - {src: "write-kv.sh.template"      ,     dest: "write-kv.sh"   , mode: "0755" }
    - {src: "read-kv.sh.template"       ,     dest: "read-kv.sh"    , mode: "0755" }

- name: 02. Deploy the private key
  ansible.builtin.copy:
    src:  ~/.ssh/id_rsa
    dest: ~/.ssh/id_rsa
    mode: "0400"
