# MySQL1 Configuration.

source-id: "mysql-replica-01"
enable-gtid: false

from:
  host: "{{ componentIPs['workstation'] | first }}"
  user: "{{ SOURCE_INFO.USER }}"
  password: "{{ SOURCE_INFO.PASSWORD }}"
  port: {{ SOURCE_INFO.PORT }}
