# MySQL1 Configuration.

source-id: "mysql-replica-01"
enable-gtid: false

from:
  host: "{{SOURCE_INFO.HOST}}"
  user: "{{SOURCE_INFO.USER}}"
  password: "{{SOURCE_INFO.PASSWORD}}"
  port: {{SOURCE_INFO.PORT}}
