name: "test"
task-mode: "all"

ignore-checking-items: ["replication_privilege", "dump_privilege"]
target-database:
  host: "{{ DEST_INFO.HOST | default(componentIPs['tidb'][0]) }}"
  port: {{ DEST_INFO.PORT | default(4000)}}
  user: "{{ DEST_INFO.USER | default('root')}}"
  password: "{{ DEST_INFO.PASSWORD | default('') }}"

mysql-instances:
-
  source-id: "mysql-replica-01"
  block-allow-list: "global"  # Use black-white-list if the DM's version <= v2.0.0-beta.2.
  mydumper-config-name: "global"
  loader-config-name: "global"

block-allow-list:                     # Use black-white-list if the DM's version <= v2.0.0-beta.2.
  global:
    do-tables:                        # The allow list of upstream tables to be migrated.
    - db-name: "{{DEST_INFO.DBNAME | default('dmtest')}}"              # The database name of the table to be migrated.
      tbl-name: "*"          # The name of the table to be migrated.

# The global configuration of the dump unit. Each instance can quote it by the configuration item name.
mydumpers:
  global:
    extra-args: " --no-locks"

loaders:
  global:
    pool-size: 16
    dir: "/DATA/dm/dumped_data"
