- name: Get the data from upstream tasks
  tags:
    - dm
  set_fact:
    componentIPs: "{{ hostvars['localhost'].get('componentIPs')['resources'] }}"

- name: Grant permission to wordpress
  shell: "{{item}}"
  with_items:
    - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'create database if not exists wordpress'"
    - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'create user if not exists wordpress@`%` identified by \"wordpress\"'"
    - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'grant select, update, insert, delete on wordpress.* to `wordpress`@`%`'"
    - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'set global tidb_enable_noop_functions=on'"
