- name: Get the data from upstream tasks
  tags:
    - dm
  set_fact:
    componentIPs: "{{ hostvars['localhost'].get('componentIPs')['resources'] }}"

- name: Start service dm-master/dm-worker, if not started
  tags:
    - dm
  become: true
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
  with_items:
    - dm-master
    - dm-worker

- name: Grant permission to wordpress
  shell: "{{item}}"
  with_items:
    - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'create database if not exists wordpress'"
    - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'create user if not exists wordpress@`%` identified by \"wordpress\"'"
    - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'grant select, update, insert, delete on wordpress.* to `wordpress`@`%`'"
    - "mysql -h {{ componentIPs['tidb'] | first }} -u root -P 4000 mysql -e 'set global tidb_enable_noop_functions=on'"

- name: Pause for 20 seconds to wait db instance up
  pause:
    seconds: 20

- name: Start the task
  tags:
    - dm
  shell: "{{ item }}"
  with_items:
    - "/opt/dm-v2.0.4-linux-amd64/bin/dmctl --master-addr {{ componentIPs['workstation'] | first }}:8261 operate-source create /var/dm/source.yaml"
    - "/opt/dm-v2.0.4-linux-amd64/bin/dmctl --master-addr {{ componentIPs['workstation'] | first }}:8261 start-task /var/dm/task.yaml"

- name: Swap the wordpress between mariadb and tidb
  when: false
  tags:
    - swap_wordpress
  become: yes
  become_user: mysql
  shell: "{{ item  }}"
  with_items:
      - /usr/bin/docker-compose -f /var/docker-compose/wordpress/docker-compose.yml down
      - /usr/bin/docker-compose -f /var/docker-compose/wordpress/docker-compose.tidb.yml up -d
