- name: Download dm binary
  become: true
  unarchive:
    src: https://download.pingcap.org/dm-v2.0.4-linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: Added the bin search path to bashrc
  lineinfile:
      line: "export PATH=/opt/dm-v2.0.4-linux-amd64/bin:$PATH"
      path: ~/.bashrc

- name: Make the file folder for the resource
  become: true
  file:
      path: "/var/dm"
      state: directory
      group: root
      owner: root

- name: Make the file folder for DM instance
  become: true
  file:
      path: "/DATA/dm"
      state: directory
      group: "{{ TIDB_USER }}"
      owner: "{{ TIDB_USER }}"

- name: Deploy the dm resources
  become: true
  template:
      src: "{{item}}"
      dest: "/var/dm/{{item}}"
      mode: '0644'
  with_items:
      - dm-master.toml
      - dm-worker.toml
      - source.yaml
      - task.yaml

- name: Deploy the service resources
  become: true
  template:
      src: "{{ item.src }}"
      dest: "/etc/systemd/system/{{ item.dest }}"
      mode: '0644'
  with_items:
      - { src: "dm-master.service" ,      dest: "dm-master.service" }
      - { src: "dm-worker.service" ,      dest: "dm-worker.service" }

- name: Print the hostname
  debug:
      msg: "This is the hostnane {{inventory_hostname}}"
